=== MISP/misp-galaxy/schema_galaxies.json
{
  "$schema": "http://json-schema.org/schema#",
  "title": "Validator for misp-galaxies - Galaxies",
  "id": "https://www.github.com/MISP/misp-galaxies/schema_galaxies.json",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "description": {
      "type": "string"
    },
    "type": {
      "type": "string"
    },
    "version": {
      "type": "integer"
    },
    "name": {
      "type": "string"
    },
    "icon": {
      "type": "string"
    },
    "uuid": {
      "type": "string"
    },
    "namespace": {
      "type": "string"
    },
    "category": {
      "type": "string",
      "enum": [
        "named-threat",
        "technique",
        "victim",
        "defensive",
        "detection",
        "targeting",
        "context",
        "reference"
      ]
    },
    "sub_category": {
      "type": "string",
      "enum": [
        "actor",
        "campaign",
        "malware",
        "tool",
        "attack-pattern",
        "technique",
        "tactic",
        "sector",
        "location",
        "target",
        "course-of-action",
        "control",
        "rule",
        "strategy",
        "data-source",
        "asset",
        "platform",
        "service",
        "producer",
        "organisation",
        "vulnerability",
        "reference"
      ]
    },
    "kill_chain_order": {
      "type": "object"
    }
  },
  "required": [
    "description",
    "type",
    "version",
    "name",
    "uuid"
  ]
}

=== MISP/misp-galaxy/galaxies/mitre-ics-tactics.json
{
  "category": "technique",
  "description": "Tactics from MITRE ATT&CK for ICS.",
  "icon": "chess-pawn",
  "name": "MITRE ATT&CK ICS Tactics",
  "namespace": "deprecated",
  "sub_category": "tactic",
  "type": "mitre-ics-tactics",
  "uuid": "e521606c-3c66-4621-9040-6f0f792fc999",
  "version": 4
}

=== MISP/misp-galaxy/galaxies/mitre-ics-groups.json
{
  "category": "named-threat",
  "description": "Adversary groups from MITRE ATT&CK for ICS.",
  "icon": "skull-crossbones",
  "name": "MITRE ATT&CK ICS Groups",
  "namespace": "deprecated",
  "sub_category": "actor",
  "type": "mitre-ics-groups",
  "uuid": "abb28bd9-fa79-4815-b5b3-fb138f433e55",
  "version": 4
}

=== MISP/misp-galaxy/galaxies/mitre-software.json
{
  "category": "named-threat",
  "description": "Malware and legitimate tools used by adversaries, tracked by MITRE ATT&CK.",
  "icon": "optin-monster",
  "name": "MITRE ATT&CK Software",
  "namespace": "mitre",
  "type": "mitre-software",
  "uuid": "69634931-c2d9-48ed-830a-b2a719407f9e",
  "version": 2
}

=== MISP/misp-galaxy/galaxies/sparta-tactics.json
{
  "category": "technique",
  "description": "SPARTA tactics published by The Aerospace Corporation.",
  "icon": "map",
  "kill_chain_order": {
    "sparta": [
      "defense-evasion",
      "execution",
      "exfiltration",
      "impact",
      "initial-access",
      "lateral-movement",
      "persistence",
      "reconnaissance",
      "resource-development"
    ]
  },
  "name": "SPARTA Tactics",
  "namespace": "sparta",
  "sub_category": "tactic",
  "type": "sparta-tactics",
  "uuid": "34faeaec-b2e8-5f39-b534-58b554f9cb5e",
  "version": 2
}

=== MISP/misp-galaxy/galaxies/producer.json
{
  "category": "context",
  "description": "List of threat intelligence producer from security vendors to CERTs including any producer of intelligence at large.",
  "icon": "book",
  "name": "Producer",
  "namespace": "misp",
  "sub_category": "producer",
  "type": "producer",
  "uuid": "2d74a15e-9c88-452e-af14-d0ecd2e9cd63",
  "version": 2
}

=== MISP/misp-galaxy/galaxies/disarm-techniques.json
{
  "category": "technique",
  "description": "DISARM is a framework designed for describing and understanding disinformation incidents.",
  "icon": "map",
  "kill_chain_order": {
    "tactics": [
      "Plan Strategy",
      "Plan Objectives",
      "Microtarget",
      "Develop Content",
      "Select Channels and Affordances",
      "Conduct Pump Priming",
      "Deliver Content",
      "Drive Offline Activity",
      "Persist in the Information Environment",
      "Assess Effectiveness",
      "Target Audience Analysis",
      "Develop Narratives",
      "Establish Assets",
      "Establish Legitimacy",
      "Maximise Exposure",
      "Drive Online Harms"
    ]
  },
  "name": "Techniques",
  "namespace": "disarm",
  "sub_category": "technique",
  "type": "disarm-techniques",
  "uuid": "a90f2bb6-11e1-58a7-9962-ba37886720ec",
  "version": 3
}

=== MISP/misp-galaxy/galaxies/mitre-enterprise-attack-malware.json
{
  "category": "named-threat",
  "description": "Name of ATT&CK software",
  "icon": "optin-monster",
  "name": "Enterprise Attack - Malware",
  "namespace": "deprecated",
  "sub_category": "malware",
  "type": "mitre-enterprise-attack-malware",
  "uuid": "fbb19af0-1707-11e8-9fd6-dbd88a04d33a",
  "version": 6
}

=== MISP/misp-galaxy/galaxies/atrm.json
{
  "category": "technique",
  "description": "The purpose of the Azure Threat Research Matrix (ATRM) is to educate readers on the potential of Azure-based tactics, techniques, and procedures (TTPs). It is not to teach how to weaponize or specifically abuse them. For this reason, some specific commands will be obfuscated or parts will be omitted to prevent abuse.",
  "icon": "map",
  "kill_chain_order": {
    "ATRM-tactics": [
      "Reconnaissance",
      "Initial Access",
      "Execution",
      "Privilege Escalation",
      "Persistence",
      "Credential Access",
      "Impact"
    ]
  },
  "name": "Azure Threat Research Matrix",
  "namespace": "microsoft",
  "sub_category": "technique",
  "type": "atrm",
  "uuid": "b541a056-154c-41e7-8a56-41db3f871c00",
  "version": 4
}
