=== MISP/misp-galaxy/schema_galaxies.json
{
  "$schema": "http://json-schema.org/schema#",
  "title": "Validator for misp-galaxies - Galaxies",
  "id": "https://www.github.com/MISP/misp-galaxies/schema_galaxies.json",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "description": {
      "type": "string"
    },
    "type": {
      "type": "string"
    },
    "version": {
      "type": "integer"
    },
    "name": {
      "type": "string"
    },
    "icon": {
      "type": "string"
    },
    "uuid": {
      "type": "string"
    },
    "namespace": {
      "type": "string"
    },
    "category": {
      "type": "string",
      "enum": [
        "named-threat",
        "technique",
        "victim",
        "defensive",
        "detection",
        "targeting",
        "context",
        "reference"
      ]
    },
    "sub_category": {
      "type": "string",
      "enum": [
        "actor",
        "campaign",
        "malware",
        "tool",
        "attack-pattern",
        "technique",
        "tactic",
        "sector",
        "location",
        "target",
        "course-of-action",
        "control",
        "rule",
        "strategy",
        "data-source",
        "asset",
        "platform",
        "service",
        "producer",
        "organisation",
        "vulnerability",
        "reference"
      ]
    },
    "kill_chain_order": {
      "type": "object"
    }
  },
  "required": [
    "description",
    "type",
    "version",
    "name",
    "uuid"
  ]
}

=== MISP/misp-galaxy/galaxies/mitre-engage-framework.json
{
  "category": "defensive",
  "description": "Activities, approaches, goals and vulnerabilities from the MITRE Engage framework.",
  "icon": "user-secret",
  "name": "MITRE Engage",
  "namespace": "mitre",
  "sub_category": "course-of-action",
  "type": "engage-framework",
  "uuid": "5dbec788-99ca-4bd7-a96f-ad0601c0f281",
  "version": 3
}

=== MISP/misp-galaxy/galaxies/mitre-mobile-attack-attack-pattern.json
{
  "category": "technique",
  "description": "ATT&CK Tactic",
  "icon": "map",
  "name": "Mobile Attack - Attack Pattern",
  "namespace": "deprecated",
  "sub_category": "attack-pattern",
  "type": "mitre-mobile-attack-attack-pattern",
  "uuid": "1c6d1332-1708-11e8-847c-e3c5643c41a5",
  "version": 6
}

=== MISP/misp-galaxy/galaxies/surveillance-vendor.json
{
  "category": "named-threat",
  "description": "List of vendors selling surveillance technologies including malware, interception devices or computer exploitation services",
  "icon": "user-shield",
  "name": "Surveillance Vendor",
  "namespace": "misp",
  "sub_category": "actor",
  "type": "surveillance-vendor",
  "uuid": "c3a92f3a-14f1-11ea-8ab7-fb9951e35286",
  "version": 2
}

=== MISP/misp-galaxy/galaxies/mitre-mobile-attack-course-of-action.json
{
  "category": "defensive",
  "description": "ATT&CK Mitigation",
  "icon": "link",
  "name": "Mobile Attack - Course of Action",
  "namespace": "deprecated",
  "sub_category": "course-of-action",
  "type": "mitre-mobile-attack-course-of-action",
  "uuid": "0282356a-1708-11e8-8f53-975633d5c03c",
  "version": 6
}

=== MISP/misp-galaxy/galaxies/mitre-enterprise-attack-course-of-action.json
{
  "category": "defensive",
  "description": "ATT&CK Mitigation",
  "icon": "link",
  "name": "Enterprise Attack - Course of Action",
  "namespace": "deprecated",
  "sub_category": "course-of-action",
  "type": "mitre-enterprise-attack-course-of-action",
  "uuid": "fb5a36c0-1707-11e8-81f5-d732b22a4982",
  "version": 6
}

=== MISP/misp-galaxy/galaxies/exploit-kit.json
{
  "category": "named-threat",
  "description": "Exploit-Kit is an enumeration of some exploitation kits used by adversaries. The list includes document, browser and router exploit kits.It's not meant to be totally exhaustive but aim at covering the most seen in the past 5 years",
  "icon": "internet-explorer",
  "name": "Exploit-Kit",
  "namespace": "misp",
  "sub_category": "tool",
  "type": "exploit-kit",
  "uuid": "6ab240ec-bd79-11e6-a4a6-cec0c932ce01",
  "version": 5
}

=== MISP/misp-galaxy/galaxies/preventive-measure.json
{
  "category": "defensive",
  "description": "Preventive measures based on the ransomware document overview as published in https://docs.google.com/spreadsheets/d/1TWS238xacAto-fLKh1n5uTsdijWdCEsGIM0Y0Hvmc5g/pubhtml# . The preventive measures are quite generic and can fit any standard Windows infrastructure and their security measures.",
  "icon": "shield-alt",
  "name": "Preventive Measure",
  "namespace": "misp",
  "sub_category": "course-of-action",
  "type": "preventive-measure",
  "uuid": "8168995b-adcd-4684-9e37-206c5771505a",
  "version": 5
}

=== MISP/misp-galaxy/galaxies/tool.json
{
  "category": "named-threat",
  "description": "Threat actors tools is an enumeration of tools used by adversaries. The list includes malware but also common software regularly used by the adversaries.",
  "icon": "optin-monster",
  "name": "Tool",
  "namespace": "misp",
  "sub_category": "tool",
  "type": "tool",
  "uuid": "9b8037f7-bc8f-4de1-a797-37266619bc0b",
  "version": 4
}
